### ISSUE TITLE
I got this error what can I do ? It looks like an error caused by cudnn's version

### ISSUE THREAD

**Issue by ghost** [antran89/two-stream-fcan#2]
@antran89  Can you help me? It's a really really strange problem.
It occurs when I build my-very-deep-caffe  by CMake&make 

myconfig:

-- ******************* Caffe Configuration Summary *******************
-- General:
--   Version           :   1.0.0-rc3
--   Git               :   6993636
--   System            :   Linux
--   C++ compiler      :   /usr/bin/c++
--   Release CXX flags :   -O3 -DNDEBUG -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Build type        :   RELEASE
-- 
--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   ON
--   BUILD_matlab      :   OFF
--   BUILD_docs        :   ON
--   CPU_ONLY          :   OFF
--   USE_OPENCV        :   ON
--   USE_LEVELDB       :   ON
--   USE_LMDB          :   ON
--   ALLOW_LMDB_NOLOCK :   ON
-- 
-- Dependencies:
--   BLAS              :   Yes (Atlas)
--   Boost             :   Yes (ver. 1.58)
--   glog              :   Yes
--   gflags            :   Yes
--   protobuf          :   Yes (ver. 2.6.1)
--   lmdb              :   Yes (ver. 0.9.17)
--   LevelDB           :   Yes (ver. 1.18)
--   Snappy            :   Yes (ver. 1.1.3)
--   OpenCV            :   Yes (ver. 2.4.13)
--   CUDA              :   Yes (ver. 9.0)
-- 
-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_61
--   cuDNN             :   Yes (ver. 7.0.3)
-- 
-- Documentaion:
--   Doxygen           :   No
--   config_file       :   
-- 
-- Install:
--   Install path      :   /usr/local
-- 
-- Configuring done

the error stack:
CMake Error at CMakeLists.txt:85 (add_dependencies):
  The dependency target "pycaffe" of target "pytest" does not exist.

-- Generating done
-- Build files have been written to: /home/gisdom/liuwentao/code/two-stream-fcan/two-stream-fcan/lib/my-very-deep-caffe/cmake-build
[  1%] Built target proto
[  1%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_absval_layer.cu.o

/code/two-stream-fcan/two-stream-fcan/lib/my-very-deep-caffe/include/caffe/util/cudnn.hpp(112): error: too few arguments in function call

1 error detected in the compilation of "/tmp/tmpxft_0000470b_00000000-4_inner_product_layer.cpp4.ii".

CMake Error at cuda_compile_1_generated_inner_product_layer.cu.o.RELEASE.cmake:281 (message):
  Error generating file
 /code/two-stream-fcan/two-stream-fcan/lib/my-very-deep-caffe/cmake-build/src/caffe/CMakeFiles/cuda_compile_1.dir/layers/./cuda_compile_1_generated_inner_product_layer.cu.o
src/caffe/CMakeFiles/caffe.dir/build.make:15484: recipe for target 'src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_inner_product_layer.cu.o' failed
make[2]: *** [src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_inner_product_layer.cu.o] Error 1

**Comment by antran89** [comment]
Hi @huanglai666,

Sorry for late reply, at the time of the code was developing, it was using cuda7.0 and cudnn 6.5. I hope it would help. If not, it is just an API change from CUDNN side. You can track it and change according the header file following the compiler error.

Sorry, I am also not much with the code, right now. I could not help you much.

**Comment by antran89** [comment]
@huanglai666 sorry it did not help you much. I should dockerize it next time.
